CREATE TABLE IF NOT EXISTS krx.etp (
    _ts TIMESTAMPTZ NOT NULL,
    기준일자 DATE NOT NULL,
    종목코드 VARCHAR(10) NOT NULL,
    종목명 VARCHAR(255) NOT NULL,
    상장타입 VARCHAR(3) NOT NULL,
    종가 DECIMAL(18, 2) NOT NULL,
    대비 DECIMAL(18, 2) NOT NULL,
    등락률 DECIMAL(5, 2),
    순자산지표가치 DECIMAL(18, 2),
    시가 DECIMAL(18, 2) NOT NULL,
    고가 DECIMAL(18, 2) NOT NULL,
    저가 DECIMAL(18, 2) NOT NULL,
    거래량 BIGINT NOT NULL,
    거래대금 BIGINT NOT NULL,
    시가총액 BIGINT NOT NULL,
    순자산지표총액 DECIMAL(18, 2),
    상장수 BIGINT NOT NULL,
    기초지수자산명 VARCHAR(255) NOT NULL,
    기초지수자산종가 DECIMAL(18, 2),
    기초지수자산대비 DECIMAL(18, 2),
    기초지수자산등락률 DECIMAL(9, 2),
    PRIMARY KEY (기준일자, 종목코드)
);
