CREATE TABLE IF NOT EXISTS krx.sto_stocks (
    _ts TIMESTAMPTZ NOT NULL,
    기준일자 DATE NOT NULL,
    종목코드 VARCHAR(6) NOT NULL,
    종목명 VARCHAR(255) NOT NULL,
    시장구분 VARCHAR(20) NOT NULL,
    소속부 VARCHAR(50),
    종가 DECIMAL(18, 2) NOT NULL,
    대비 DECIMAL(18, 2) NOT NULL,
    등락률 DECIMAL(9, 2) NOT NULL,
    시가 DECIMAL(18, 2) NOT NULL,
    고가 DECIMAL(18, 2) NOT NULL,
    저가 DECIMAL(18, 2) NOT NULL,
    거래량 BIGINT NOT NULL,
    거래대금 BIGINT NOT NULL,
    시가총액 BIGINT NOT NULL,
    상장주식수 BIGINT NOT NULL,
    PRIMARY KEY (기준일자, 종목코드)
);